apiVersion: v1
kind: ReplicationController
metadata:
 creationTimestamp: null
labels:
 service: membersrvc
name: membersrvc
namespace: default
spec:
 replicas: 1
selector:
 service: membersrvc
template:
 metadata:
 creationTimestamp: null
labels:
 service: membersrvc
spec:
 containers:
 -command:
 -membersrvc
image: hyperledger / fabric - membersrvc
imagePullPolicy: ""
name: membersrvc
ports:
 -containerPort: 7054
resources: {}
restartPolicy: Always
serviceAccountName: ""
volumes: null
status:
 replicas: 0