apiVersion: v1
kind: ReplicationController
metadata:
 creationTimestamp: null
labels:
 service: vp0
name: vp0
namespace: $ {
 NAMESPACE
}
spec:
 replicas: 1
selector:
 service: vp0
template:
 metadata:
 creationTimestamp: null
labels:
 service: vp0
spec:
 containers:
 -command:
 -sh - -c - sleep 5;
peer node start--peer - chaincodedev
env:
 -name: CORE_PEER_ADDRESSAUTODETECT
value: "true" - name: CORE_VM_ENDPOINT
value: unix: ///var/run/docker.sock
 -name: CORE_LOGGING_LEVEL
value: DEBUG - name: CORE_PEER_ID
value: vp0 - name: CORE_PEER_PKI_ECA_PADDR
value: membersrvc: 7054 - name: CORE_PEER_PKI_TCA_PADDR
value: membersrvc: 7054 - name: CORE_PEER_PKI_TLSCA_PADDR
value: membersrvc: 7054 - name: CORE_SECURITY_ENABLED
value: "false" - name: CORE_SECURITY_ENROLLID
value: test_vp0 - name: CORE_SECURITY_ENROLLSECRET
value: MwYpmSRjupbT
image: hyperledger / fabric - peer
imagePullPolicy: ""
name: vp0
ports:
 -containerPort: 7050 - containerPort: 7051 - containerPort: 7053
resources: {}
restartPolicy: Always
serviceAccountName: ""
volumes: null
status:
 replicas: 0